/* Automatically generated by po2tbl.sed from dumb.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Picked up body armour.", 2},
  {"You found the mega armour!", 3},
  {"Picked up a stimpak.", 4},
  {"Picked up a medikit.", 5},
  {"Megasphere!", 6},
  {"You found a backpack full of ammo!", 7},
  {"Computer area map!", 8},
  {"You got the red key!", 9},
  {"You already have that key.", 10},
  {"You got the blue key!", 11},
  {"You got the yellow key!", 12},
  {"You got the red skull key!", 13},
  {"You got the blue skull key!", 14},
  {"You got the yellow skull key!", 15},
  {"Invincibility... Oh my God!", 16},
  {"Suddenly you can't see yourself.", 17},
  {"Radiation shielding suit!", 18},
  {"You got the light amplification goggles!", 19},
  {"You got the chainsaw... Find some meat!", 20},
  {"You smell blood!", 21},
  {"You got the shotgun!", 22},
  {"You got the super shotgun!", 23},
  {"You got the chaingun!", 24},
  {"You got the rocket launcher!", 25},
  {"You got the plasma rifle!", 26},
  {"You got the BFG!", 27},
  {"ticks to pass before key autorelease or 0", 28},
  {"ticks to pass before shift autorelease or 0", 29},
  {"aalib_input must be initialised after aalib_video", 30},
  {"AA-lib keyboard driver supports AA_SENDRELEASE", 31},
  {"AA-lib keyboard driver doesn't support AA_SENDRELEASE", 32},
  {"very fast (but not as perfect)", 33},
  {"<disabled at compile time>", 34},
  {"brightness (0-255)", 35},
  {"contrast (0-255)", 36},
  {"gamma (1000 corresponds to 1.0)", 37},
  {"multiply factor for dim color (ditto)", 38},
  {"multiply factor for bold color (ditto)", 39},
  {"dithering type", 40},
  {"range of random value to add to each pixel (0-inf)", 41},
  {"invert the whole screen", 42},
  {"name of the font you use", 43},
  {"use the normal attribute", 44},
  {"use the bold (double bright) attribute", 45},
  {"use the boldfont attribute", 46},
  {"use the dim (half bright) attribute", 47},
  {"use the reverse attribute", 48},
  {"use all 256 characters", 49},
  {"use eight-bit ASCII", 50},
  {"AA-lib initialisation failed", 51},
  {"AA-lib doesn't know of font `%s'", 52},
  {"The following fonts are available:", 53},
  {"Bad AnimTexNum (%d)", 54},
  {"too many banners", 55},
  {"init banner %d", 56},
  {"Quit", 57},
  {"Move forward", 58},
  {"Move backward", 59},
  {"Turn left", 60},
  {"Turn right", 61},
  {"Turn around", 62},
  {"Sidestep left", 63},
  {"Sidestep right", 64},
  {"Jump / Swim/Fly up", 65},
  {"Duck / Swim/Fly down", 66},
  {"Look up", 67},
  {"Look down", 68},
  {"Aim up", 69},
  {"Aim down", 70},
  {"Center view", 71},
  {"Run", 72},
  {"Strafe", 73},
  {"Activate", 74},
  {"Shoot", 75},
  {"Shoot special", 76},
  {"Select next weapon", 77},
  {"Select previous weapon", 78},
  {"Select weapon 0", 79},
  {"Select weapon 1", 80},
  {"Select weapon 2", 81},
  {"Select weapon 3", 82},
  {"Select weapon 4", 83},
  {"Select weapon 5", 84},
  {"Select weapon 6", 85},
  {"Select weapon 7", 86},
  {"Select weapon 8", 87},
  {"Select weapon 9", 88},
  {"Use item", 89},
  {"Next item", 90},
  {"Previous item", 91},
  {"disable mouse support", 92},
  {"mouse sensitivity x-axis (4)", 93},
  {"mouse sensitivity y-axis (2)", 94},
  {"Can't initialize mouse! Missing driver?", 95},
  {"dont try to use page flipping", 96},
  {"use VESA 2.0 linear modes (UniVBE preferred)", 97},
  {"Can't initialize video: %s", 98},
  {"Using page flipping", 99},
  {"Using double buffering", 100},
  {"Using two-stage double buffering", 101},
  {"Video mode: %s (%s)", 102},
  {"got SIGALRM: renderer must have gotten stuck...", 103},
  {"save configuration after every run", 104},
  {"save configuration this time only", 105},
  {"specify wadfiles to load", 106},
  {"directories in which to look for wads", 107},
  {"filename of doom.wad", 108},
  {"filename of doom2.wad", 109},
  {"filename of doom4dum.wad", 110},
  {"set starting map", 111},
  {"don't log to the screen", 112},
  {"don't create any objects, just preview the map", 113},
  {"set difficulty level", 114},
  {"disable sound", 115},
  {"video width", 116},
  {"video height", 117},
  {"video depth (in bytes/pixel)", 118},
  {"log to this file", 119},
  {"record player actions to file", 120},
  {"playback player actions from file", 121},
  {"hide gettables and banners", 122},
  {"show a crosshair in the center of the view", 123},
  {"multiply the pixels x size", 124},
  {"multiply the pixels y size", 125},
  {"skip pixels when multiplying x size", 126},
  {"skip pixels when multiplying y size", 127},
  {"load textures before game starts", 128},
  {"angle from forward of player view", 129},
  {"offset from center of player view", 130},
  {"network play: slave mode", 131},
  {"network play: master mode", 132},
  {"force single player mode", 133},
  {"angle to rotate view by", 134},
  {"maximum frames to render", 135},
  {"enable 3rd person perspective", 136},
  {"Input Driver", 137},
  {"Video Driver", 138},
  {"Sound Driver", 139},
  {"Network Driver", 140},
  {"Network Play", 141},
  {"General Game Control", 142},
  {"Player Interface", 143},
  {"Keyboard Mapping", 144},
  {"\
This program is free software; you may redistribute it under the terms of\n\
the GNU General Public License.  This program has absolutely no warranty.\n", 145},
  {"Preloading wall textures", 146},
  {"Preloading floor/ceiling textures", 147},
  {"Preloading sprites", 148},
  {"\
This program was compiled to use MMX, but your processor\n\
does not appear to support it.\n", 149},
  {"Read configuration from %s", 150},
  {"network mode: slave", 151},
  {"network mode: master", 152},
  {"Unsupported BPP=%d", 153},
  {"Can't find sector for player", 154},
  {"starting game", 155},
  {"Demo ran out...", 156},
  {"saving snapshot...", 157},
  {"snapshot done", 158},
  {"%d ticks passed with MAXTICKS=%d", 159},
  {"WARNING: this system is running faster than the timer resolution", 160},
  {"Try running DUMB in a larger window.", 161},
  {"You died.  Too bad...", 162},
  {"%d frames, %d seconds, %f fps", 163},
  {"Saving config to %s", 164},
  {"dummy input: always quit", 165},
  {"processor timing overcompensation tweak", 166},
  {"forward speed", 167},
  {"strafe speed", 168},
  {"turning speed", 169},
  {"jumping speed", 170},
  {"Player %d warped", 171},
  {"Player %d cheated", 172},
  {"Player %d wibbled loudly", 173},
  {"Player %d returned", 174},
  {"Player %d smashes pumpkins", 175},
  {"warning: no gettables", 176},
  {"init %d gettables", 177},
  {"GGI: ggiInit failed.", 178},
  {"GGI: ggiOpen failed.", 179},
  {"Bad BPP (%d) in init_video", 180},
  {"Depth %d not supported.", 181},
  {"Mode not supported by LibGGI.", 182},
  {"init_video in copying mode pagelen=%d", 183},
  {"NULL keyname for keycode 0x%08lX", 184},
  {"No action for keyname \"%s\"", 185},
  {"--- begin keymap debug dump", 186},
  {"--- end keymap debug dump", 187},
  {"attempt to resize keymap under its length", 188},
  {"Keys to quit DUMB", 189},
  {"Keys to move forward", 190},
  {"Keys to move backward", 191},
  {"Keys to turn left", 192},
  {"Keys to turn right", 193},
  {"(not implemented)", 194},
  {"Keys to sidestep left", 195},
  {"Keys to sidestep right", 196},
  {"Keys to jump / swim/fly up", 197},
  {"Keys to duck / swim/fly down", 198},
  {"Keys to look up", 199},
  {"Keys to look down", 200},
  {"Keys to aim up", 201},
  {"Keys to aim down", 202},
  {"Keys to look straight ahead", 203},
  {"Keys to hold to move faster", 204},
  {"Keys to hold to sidestep instead of turning", 205},
  {"Keys to activate switches and doors", 206},
  {"Keys to shoot with the selected weapon", 207},
  {"Keys to select the next weapon", 208},
  {"Keys to select the previous weapon", 209},
  {"Keys to select weapon 0", 210},
  {"Keys to select weapon 1", 211},
  {"Keys to select weapon 2", 212},
  {"Keys to select weapon 3", 213},
  {"Keys to select weapon 4", 214},
  {"Keys to select weapon 5", 215},
  {"Keys to select weapon 6", 216},
  {"Keys to select weapon 7", 217},
  {"Keys to select weapon 8", 218},
  {"Keys to select weapon 9", 219},
  {"Keys to use the selected item", 220},
  {"Keys to select the next item", 221},
  {"Keys to select the previous item", 222},
  {"Keymap is empty, installing defaults.", 223},
  {"Loading %s: difficulty=%d", 224},
  {"Loading %s grain=%d align=%d", 225},
  {"levdata: %s will not be aligned correctly", 226},
  {"Init %d %s", 227},
  {"Uh-oh: no player!", 228},
  {"Freeing level data for %s", 229},
  {"Pre-freeing %s for %s", 230},
  {"bad maplumptype (%d) in apply_update()", 231},
  {"no decode func for maplumptype %d", 232},
  {"out of range item (%d) in apply_update()", 233},
  {"got plinfo_update for player with no plinfo?", 234},
  {"Ran out of thing slots", 235},
  {"Couldn't find protothing ID=%d", 236},
  {"diffchk: strange difficulty??? (%d)", 237},
  {"warning: no LEVINFO lump for this game", 238},
  {"Init %d levels", 239},
  {"bogus levinfo pointer in levinfo_load", 240},
  {"no levinfo for %s, so can't find next level", 241},
  {"Loaded %d linetypes, of which %d scrolling", 242},
  {"Failed to find LINETYPE in wad", 243},
  {"Loaded %d sectortypes", 244},
  {"Failed to find SECTTYPE in wad", 245},
  {"mouse type", 246},
  {"mouse device", 247},
  {"Console open failed", 248},
  {"Console in raw mode", 249},
  {"maximum pages to use for flipping", 250},
  {"minimum pages to use for flipping", 251},
  {"No linear framebuf? Try running as root (not just suid root)", 252},
  {"Too little video RAM, or no linear fb: linearlen=%d pagelen=%d", 253},
  {"init_video in copying mode linearlen=%d pagelen=%d npages=%d", 254},
  {"init_video in flipping mode linearlen=%d pagelen=%d npages=%d", 255},
  {"fontless message: %s", 256},
  {"warning: MessageDomain not set", 257},
  {"too many stations", 258},
  {"network driver doesn't know how to gethostname()?", 259},
  {"packet length not a multiple of 4 (type=%c len=%lu)", 260},
  {"msec to wait for slaves to init", 261},
  {"msec to wait for slaves to catch up", 262},
  {"msec to wait for master", 263},
  {"msec to allow slaves to get behind", 264},
  {"run network asychronously", 265},
  {"time between sending acks", 266},
  {"sending slave-init to %s (station %d)", 267},
  {"sending slave-init packets...", 268},
  {"waiting for slaves to initialise", 269},
  {"all slaves up", 270},
  {"sending init-request", 271},
  {"waiting for slave init info from master", 272},
  {"waiting for slave '%s' (%d) to catch up", 273},
  {"slave '%s' (%d) seems to be dead", 274},
  {"inconsistent packet length %lu > %lu", 275},
  {"init request from %s ignored", 276},
  {"got init request: setting up new station %d", 277},
  {"init pkt length mismatch: got %d, expecting %lu", 278},
  {"protocol version mismatch: got %d, expecting %d", 279},
  {"strange packet type (%c) in netplay_poll()", 280},
  {"station %s (%d) lives!", 281},
  {"start=%d end=%d", 282},
  {"problems with fb coords in draw_wall_segment", 283},
  {"problems with fb coords in draw_sky_segment", 284},
  {"problems with fb coords in draw_obj", 285},
  {"Column (%d) off edge of sprite (width=%d)", 286},
  {"init_renderer fb dimensions (%d,%d) view (%d,%d) bpp=%d", 287},
  {"fb1=%d fb2=%d for wall %d", 288},
  {"Too many wall start_events column=%d", 289},
  {"Too many obj start_events", 290},
  {"active_count=%d at rw_column %d", 291},
  {"active_obj_count=%d at rw_column %d", 292},
  {"Too many active objects (%d)", 293},
  {"unimplemented LT_TermType %d", 294},
  {"find_spot: found %d", 295},
  {"find_spot: no spot found", 296},
  {"boss tag effect on sector %d", 297},
  {"strange WallHitType (%d) in thing_hit_wall()", 298},
  {"player is not allowed to activate type %d", 299},
  {"non-player is not allowed to activate type %d", 300},
  {"You need a key!", 301},
  {"line %d is having something done to it by thing %d", 302},
  {"tried manual action on wall with no back?", 303},
  {"tried manual_f action on wall with no front?", 304},
  {"strange lumptype (%d) while performing actions", 305},
  {"Obj %d is heatseeking %d", 306},
  {"thing %d is out to get %d!", 307},
  {"thing %d took %d damage (%d/%d hits, %d/%d armour)", 308},
  {"melee: %d's attack on %d failed", 309},
  {"Thing %d becomes type %d; old type was %d", 310},
  {"UDP port to listen on", 311},
  {"IP broadcast address", 312},
  {"Host-specific port numbers will be ignored when broadcasting", 313},
  {"Invalid port number `%s' -- assuming %d", 314},
  {"gethostbyname() failed for '%s': %s", 315},
  {"recvfrom(sock=%d, ...): %s", 316},
  {"data from new station (%08x)", 317},
  {"blocking UDP socket: %s", 318},
  {"peek recvfrom(sock=%d, ...): %s", 319},
  {"unblocking UDP socket: %s", 320},
  {"sendto(sock=%d, ...): %s", 321},
  {"broadcast sendto(sock=%d, ...): %s", 322},
  {"gethostname: %s", 323},
  {"creating UDP socket: %s", 324},
  {"binding UDP socket: %s", 325},
  {"udp: broadcast access denied (try running as root)", 326},
  {"udp broadcast: %d packets, %d bytes, avg len %d", 327},
  {"udp unicast:   %d packets, %d bytes, avg len %d", 328},
  {"udp total:     %d packets, %d bytes, avg len %d", 329},
  {"copying ceiling texture from %d to %d", 330},
  {"copying floor texture from %d to %d", 331},
  {"sector event terminated OK s=%d type=%d", 332},
  {"do_sector_event: strange eventtype (%d)", 333},
  {"sector %d has no center?", 334},
  {"do_thing_event: teleporting %d", 335},
  {"do_thing_event: strange eventtype (%d)", 336},
  {"do_side_event: switching %d on", 337},
  {"do_side_event: switching %d off", 338},
  {"do_side_event: strange eventtype (%d)", 339},
  {"No free event in insert_event(%d,%d,%d)", 340},
  {"event %d passed its stop date", 341},
  {"event %d entering stage %d entity %d", 342},
  {"Strange lumptype %d in um_events", 343},
  {"%d is being crushed, but not by sector %d ???", 344},
  {"climbing, factor=%d", 345},
  {"VGA-linear=%x", 346},
  {"GL-flipmode=%d", 347},
  {"allow use of XFree86's DGA extension", 348},
  {"allow use of the MIT shared memory extension", 349},
  {"synchronous I/O (for debugging)", 350},
  {"dump core on X errors (for debugging)", 351},
  {"allow use of the XKeyboard extension", 352},
  {"grab the keyboard focus while DUMB runs", 353},
  {"Shm Attaches=%d", 354},
  {"x11_video: Can't open default display", 355},
  {"DGA viewport=%d,%d,%d", 356},
  {"X server doesn't support DGA", 357},
  {"using XF86-DGA", 358},
  {"XCreateWindow failed", 359},
  {"win-id=%ld", 360},
  {"XShmCreateImage failed", 361},
  {"shmget failed", 362},
  {"XShm disabled: are we not local?", 363},
  {"using XShm", 364},
  {"XCreateImage failed", 365},
  {"using Xlib Images (slow)", 366},
  {"X colormap came back as None.  Probably some strange visual.", 367},
  {"cmap-id=%ld", 368},
  {"Installing colormap", 369},
  {"Got XEvent", 370},
  {"Got some weird event type: %d", 371},
  {"Got KeyPress", 372},
  {"Got KeyRelease", 373},
  {"EnterNotify received\n", 374},
  {"LeaveNotify received\n", 375},
  {"x11_input must be initialised after x11_video", 376},
  {"XKB %d.%d in Xlib is incompatible with our %d.%d", 377},
  {"XKB %d.%d in X server is incompatible with our %d.%d", 378},
  {"X server does not support DetectableAutorepeat", 379},
  {"DetectableAutorepeat enabled via XKB", 380},
  {"keyboard grab failed!", 381},
  {"wand crystal", 382},
  {"crystal geode", 383},
  {"ethereal arrows", 384},
  {"quiver of ethereal arrows", 385},
  {"claw orb", 386},
  {"energy orb", 387},
  {"bag of holding", 388},
  {"morph ovum", 389},
  {"time bomb of the ancients", 390},
  {"map scroll", 391},
  {"shadowsphere", 392},
  {"crystal vial", 393},
  {"quartz flask", 394},
  {"wings of wrath", 395},
  {"ring of invincibility", 396},
  {"silver shield", 397},
  {"tome of power", 398},
  {"green key", 399},
  {"blue key", 400},
  {"yellow key", 401},
  {"gauntlets of the necromancer", 402},
  {"ethereal crossbow", 403},
  {"dragon claw", 404},
  {"Couldn't initialize sound: %s", 405},
  {"Sound driver: %s (%s)", 406},
  {"couldn't find SOUNDS lump", 407},
  {"Loaded %d sounds", 408},
  {"play_dsound got bad sound id (%d)", 409},
  {"Font lump %s is too short for header", 410},
  {"init %lu characters in font %s", 411},
  {"No font defined for FontMapping %d", 412},
  {"FONTMAP lump is too short for header", 413},
  {"init %lu font mappings", 414},
  {"Lump %s is too short", 415},
  {"Gettable block chain corrupted", 416},
  {"Sound device file to open", 417},
  {"Maximum allowed bits per channel", 418},
  {"Force monaural sound", 419},
  {"init_sound: fd=%d fragsize=%d (%d bytes)", 420},
  {"init_sound: speed=%d window=%d (%f seconds) slush=%d", 421},
  {"init_sound: can't get sound format list: %s", 422},
  {"init_sound: no supported formats found", 423},
  {"init_sound: set format failed: %s", 424},
  {"init_sound: driver changed the format to something we don't support", 425},
  {"init_sound: set stereo failed: %s", 426},
  {"init_sound: mono not available, using stereo", 427},
  {"init_sound: stereo not available, using mono", 428},
  {"init_sound: set fragsize failed: %s", 429},
  {"init_sound: set speed failed: %s", 430},
  {"init_sound: sample rate %d Hz not available, using %d Hz", 431},
  {"poll_sound: underrun detected", 432},
  {"Lump %s is of wrong type", 433},
  {"Lump %s has format version %d; should be %d", 434},
  {"Bits per channel", 435},
  {"Stereo sound instead of mono", 436},
  {"init_sound: no sounddevice present", 437},
  {"Failed to allocate PCMWAVEFORMAT struct", 438},
  {"waveOutOpen failed - status = %d\n", 439},
  {"Failed to allocate WAVEHDR struct", 440},
  {"Failed to allocate shared audio buffer", 441},
  {"init_sound: mme_handle=%d fragsize=%d (%ld bytes)", 442},
  {"init_sound: speed=%d slush=%d", 443},
  {"waveOutWrite failed", 444},
  {"wanted rot %c for sprite %s phase %d???", 445},
  {"Can't find sprite %s, ph=%d (%c) rot=%c", 446},
  {"Can't find ThingPhase id=%d", 447},
  {"init %d protothings", 448},
  {"ProtoThing block chain corrupted", 449},
  {"Unterminated string in PROTOS lump", 450},
  {"sndmix_sample_size: strange format %d", 451},
  {"sndmix_play_sound: out of slots (sound discarded)", 452},
  {"sndmix_calc_frag: strange format %d", 453},
  {"Bad BPP value in paste_pict", 454},
  {"Bad BPP value in paste_jpatch", 455},
  {"... but should be %d", 456},
  {"No metatexture lumps in WAD", 457},
  {"%s has %d wall textures", 458},
  {"Can't find any sprites in WAD", 459},
  {"too short sprite: %s", 460},
  {"Init %d sprites", 461},
  {"Bad lumpnum for texture %s in load_sprite()", 462},
  {"Can't find sprite texture %s", 463},
  {"Can't find any flats in WAD", 464},
  {"funny length (%d) for flat %s", 465},
  {"Init %d flats", 466},
  {"Can't find flat texture %s", 467},
  {"Patchnum %d (%s) doesn't exist", 468},
  {"loading patchnum %d (%s)", 469},
  {"init_walltexs(): %d textures", 470},
  {"Can't find wall texture %s", 471},
  {"wtex \"%s\" is unaligned with offset %ld!", 472},
  {"using one-patch kludge for %s", 473},
  {"load_walltex %s at %d bpp", 474},
  {"%s: %d patches", 475},
  {"Can't make sense of patch #%d, texture %s", 476},
  {"%s: loaded", 477},
  {"too many misc textures", 478},
  {"get_texture_num: unsupported texture type (%d)", 479},
  {"get_texture_bynum: unsupported texture type (%d)", 480},
  {"count_textures: unsupported texture type (%d)", 481},
  {"init_textures(): done", 482},
  {"Strange texture type (0x%x) in free_texels", 483},
  {"Strange BPP value (%d) in load_texels", 484},
  {"Strange texture type (0x%x) in load_texels", 485},
  {"Report bugs to <%s>.\n", 486},
  {"`%s' is not an option.  I'll use `%s' instead.\n", 487},
  {"switch requires an argument -- %s\n", 488},
  {"internal error: set_conf(): strange type %d\n", 489},
  {"\
; %s\n\
; this file was created automatically, but you can modify it if you want\n", 490},
  {"\
\n\
; Module `%s': %s\n", 491},
  {"internal error: save_conf(): strange type %d, treating as int\n", 492},
  {"Missing quote in configuration file\n", 493},
  {"Trailing backslash in configuration file\n", 494},
  {"`%s' is not a switch I recognise\n", 495},
  {"\
I don't understand your command line.  The token which is causing trouble\n\
is `%s'.\n\
\n", 496},
  {"\
usage: %s [switch [parameter]] [switch [parameter]]...\n\
\n\
For a list of all switches available, invoke %s --help all\n\
\n\
Or, for switches relating to a particular module, %s --help <module>\n\
where module is one of: all", 497},
  {"\
\n\
\n\
For information on a particular switch: %s --help <switch>\n\
\n", 498},
  {"\
You can abbreviate `--help' as `-\\?'.\n\
\n", 499},
  {"Module `%s': %s\n", 500},
  {"<no configurable items>\n", 501},
  {" <integer>", 502},
  {" <enum>", 503},
  {" <string>", 504},
  {" <list>", 505},
  {" <internal error: strange type %d>", 506},
  {" (short form -%c)", 507},
  {"\
Help for %s:\n\
  `%s'\n", 508},
  {"  Type=%s\n", 509},
  {"Integer", 510},
  {"  Default=%d\n", 511},
  {"Boolean", 512},
  {"Enumerated", 513},
  {"  Default=%s\n", 514},
  {"  Values=", 515},
  {"String", 516},
  {"List", 517},
  {"  Type=%d (internal error)\n", 518},
  {"  Short Form=-%c\n", 519},
  {"  Maxlen=%d\n", 520},
  {"  Cannot be saved in a config file.\n", 521},
  {"Copyright (C) %s %s\n", 522},
  {"%s: opening log file: %s", 523},
  {"Normal exit.", 524},
  {"%d errors occured.", 525},
  {"A fatal error occured.", 526},
  {"System error message (may be unrelated)", 527},
  {"%s: munmapping %lu bytes: %s", 528},
  {"munmapping %lu bytes: %s", 529},
  {"<unknown file>", 530},
  {"%s: unexpected EOF", 531},
  {"%s: opening: %s", 532},
  {"%s: closing: %s", 533},
  {"%s: lseek failed: %s", 534},
  {"safe_realloc(%p, 0) called", 535},
  {"out of memory reallocating %lu bytes (old=%p)", 536},
  {"out of memory allocating %lu bytes", 537},
  {"Attempt to free NULL.", 538},
  {"mmapping %lu zero bytes: %s", 539},
  {"%s: mmapping %lu bytes: %s", 540},
  {"munmapping %lu bytes @ %p: %s", 541},
  {"Bad lumpnum in load_lump", 542},
  {"Bad lumpnum in free_lump", 543},
  {"wad hashtable: %d entries unused, max chain %d", 544},
  {"%s: lump %d has no name", 545},
  {"%s: lump %d is too big for wad", 546},
  {"%s is too short to be a valid wadfile", 547},
  {"%s: mmap failed: %s", 548},
  {"%s mapped at %p (%lu bytes)", 549},
  {"Bad signature on %s: expecting %s, got %.4s", 550},
  {"directory for %s would be beyond end of file; truncating", 551},
  {"%s: %s, %d lumps, dir @ %d", 552},
  {"Can't find lump marker %s (lump %s)", 553},
  {"Can't find lump %s:%s", 554},
  {"Can't find lump %s", 555},
  {"Can't find end-marker %s", 556},
  {"End-marker %s occurs before lump %s", 557},
  {"Bad lumpnum (%x) in get_lump_*", 558},
  {"%s: can't open: %s", 559},
  {"%s: short write: %s", 560},
  {"%s: can't rewind: %s", 561},
  {"%s: can't get position: %s", 562},
  {"%s: can't align: %s", 563},
  {"deleting sector %u which has sides", 564},
  {"sector deleted under thing %d", 565},
  {"Saving level %s to %s", 566},
  {"%s: option `%s' is ambiguous\n", 567},
  {"%s: option `--%s' doesn't allow an argument\n", 568},
  {"%s: option `%c%s' doesn't allow an argument\n", 569},
  {"%s: option `%s' requires an argument\n", 570},
  {"%s: unrecognized option `--%s'\n", 571},
  {"%s: unrecognized option `%c%s'\n", 572},
  {"%s: illegal option -- %c\n", 573},
  {"%s: invalid option -- %c\n", 574},
  {"%s: option requires an argument -- %c\n", 575},
  {"%s: option `-W %s' is ambiguous\n", 576},
  {"%s: option `-W %s' doesn't allow an argument\n", 577},
  {"Success", 578},
  {"Host not found (Authoritative)", 579},
  {"Host not found (Unauthoritative)", 580},
  {"Unrecoverable error", 581},
  {"Name is valid but has no address", 582},
  {"Unknown error", 583},
  {"Name expected after AnimTex", 584},
  {"To (%d) must exceed Parm (%d)", 585},
  {"Tag must come before any Texture", 586},
  {"%5d animtexes\n", 587},
  {"Formatted string is too long at char %#04lx", 588},
  {"%5u fonts:", 589},
  {"%5u font mappings\n", 590},
  {"Name expected after Gettable", 591},
  {"%5d gettables", 592},
  {"Gettable name parameter expected", 593},
  {"Gettable name `%s' unrecognised", 594},
  {"%5d levinfos\n", 595},
  {"unrecognised levelname: %s\n", 596},
  {"Name expected after Line/SectorType", 597},
  {"ID %d (%s) not unique (clashes with %s)", 598},
  {"Too many actions (max %d)", 599},
  {"Lumptype expected after Action", 600},
  {"Eventtype expected after Action", 601},
  {"%5d linetypes\n", 602},
  {"%5d sectortypes\n", 603},
  {"Termtype parameter expected", 604},
  {"Strange lumptype", 605},
  {"Strange eventtype", 606},
  {"Eventtype expected after WaitFor", 607},
  {"String is too long (max %d characters)", 608},
  {"String parameter expected.  Try --fake-strings", 609},
  {"String parameter expected", 610},
  {"Invalid escape sequence `\\%c'", 611},
  {"Must be exactly one character", 612},
  {"Option `--fake-strings' could help", 613},
  {"Character parameter expected", 614},
  {"Integer expected", 615},
  {"Integer or newline expected", 616},
  {"Integer %.*s is not in range (%ld to %ld)", 617},
  {"Integer %.*s is not in range (%lu to %lu)", 618},
  {"Floating-point parameter expected", 619},
  {"Time parameter expected", 620},
  {"Speed parameter expected", 621},
  {"Arc parameter expected", 622},
  {"Arc parameter or newline expected", 623},
  {"Strange timing unit", 624},
  {"Strange speed unit", 625},
  {"Obsolete arc syntax; use `0deg'", 626},
  {"Obsolete arc syntax; use `pi/%d'", 627},
  {"Divisor expected after `pi/'", 628},
  {"Strange arc unit", 629},
  {"Name expected after PhaseTable", 630},
  {"Name expected after Phase", 631},
  {"%5d phase tables\n", 632},
  {"Phase table name parameter expected", 633},
  {"Phase table name `%s' unrecognised", 634},
  {"You need to specify a phasetable first", 635},
  {"Phase name parameter expected", 636},
  {"Phase name `%s' unrecognised", 637},
  {"Name expected after Proto", 638},
  {"%5d protos: sorting", 639},
  {", writing", 640},
  {"warning: proto %s (%d) has no phasetable\n", 641},
  {"Proto name parameter expected", 642},
  {"Proto name `%s' unrecognised", 643},
  {"`TurnWhenHitting' is now called `TurnOwner'", 644},
  {"`BulletKludge' is now called `BecomesBlood'", 645},
  {"`FastShoot' is obsolete; `Nasty' is the closest we have", 646},
  {"`Flying' is obsolete; use `CanFly'", 647},
  {"ID %d not unique (clashes with %s)", 648},
  {"Syntax error", 649},
  {"\
Usage: %s -o WADFILE\n\
   or: %s -d DIRECTORY\n\
Compile .pt files to various lumps used by DUMB.  Ptcomp reads .pt source\n\
from standard input, and creates the following lumps: PHASES, PROTOS,\n\
GETTABLE, LINETYPE, SECTTYPE, SOUNDS, ANIMTEX and LEVINFO.  It saves them\n\
either in WADFILE or as *.lump files in DIRECTORY.\n\
\n", 650},
  {"\
  -o, --output-wad=WADFILE          create WADFILE containing the lumps\n\
  -d, --output-directory=DIRECTORY  write *.lump files in DIRECTORY\n\
      --fake-strings                translate name tokens to strings\n\
                                    where needed\n\
      --help                        display this help and exit\n\
      --version                     output version information and exit\n\
\n", 651},
  {"%s: Deprecated usage.  Assuming you meant:\n", 652},
  {"Try `%s --help' for more information.\n", 653},
  {"%s: You must use `-d DIRECTORY' or `-o WADFILE'\n", 654},
  {"stdin", 655},
  {"%s: compiling...\n", 656},
  {"Name expected after SoundType", 657},
  {"Too many sound redirects (max %d)", 658},
  {"%5d sounds\n", 659},
  {"Sound name parameter expected", 660},
  {"Soundtype `%s' redefined", 661},
  {"NUL characters are not allowed", 662},
  {"Unexpected EOF", 663},
  {"In string which begins here:", 664},
  {"Line number is too large", 665},
  {"Line number expected", 666},
  {"`\"' expected before filename", 667},
  {"`\"' expected after filename", 668},
  {"Warning: ", 669},
  {" at end of file\n", 670},
  {" at end of line\n", 671},
  {" at long string\n", 672},
  {" at string %s\n", 673},
  {" at `%s'\n", 674},
  {"%s: initializing map\n", 675},
  {"%s: setting difficulty\n", 676},
  {"\
Usage: %s [OPTION]... IWAD [PWAD]...\n\
Load a map and operate on it.\n\
\n", 677},
  {"\
  Settings:\n\
  -m, --map=NAME             which map to load (default %s)\n\
      --difficulty=N         1=easy ... 5=hard (default all)\n\
      --verbose              explain what is being done\n", 678},
  {"\
  Operations:\n\
      --statistics           display statistics on the whole map\n\
      --sector-sides=SECTOR  list sides in SECTOR\n\
      --sector-things=SECTOR list things in SECTOR\n\
      --thing-sectors=THING  list sectors THING is in\n\
      --set-name=NAME        set the name of the map to NAME\n\
      --set-long-name=NAME   set the long name of the map to NAME\n\
      --output-doom=FILE     save the map to FILE in Doom format.\n\
                             .wad won't be appended automatically.\n", 679},
  {"\
  Other:\n\
      --help                 display this help and exit\n\
      --version              output version information and exit\n\
\n", 680},
  {"%s: --difficulty given twice\n", 681},
  {"%s: invalid difficulty `%s'\n", 682},
  {"%s: difficulty must be between 1 and 5\n", 683},
  {"%s: invalid sector number `%s'\n", 684},
  {"%s: invalid thing number `%s'\n", 685},
  {"%s: opening files\n", 686},
  {"%s: missing IWAD argument\n", 687},
  {"Statistics for level %s:", 688},
  {"\
\n\
\tVertices: ", 689},
  {"\
\n\
\tSectors: ", 690},
  {"\
\n\
\tSides: ", 691},
  {"\
\n\
\tLines: ", 692},
  {"\
\n\
\tThings: ", 693},
  {"%u alloced, %u inited, %u free", 694},
  {"%s: sector number %d doesn't exist\n", 695},
  {"Sides in sector %d:\n", 696},
  {"\tside %5d, line %5d\n", 697},
  {"\tside %5d, line %5d, opposite sector %5d\n", 698},
  {"Things in sector %d:", 699},
  {"%s: thing number %d doesn't exist\n", 700},
  {"Sectors thing %d is in:", 701},
  {"%s: invalid integer `%s'\n", 702},
  {"%s: integer `%s' is too large\n", 703},
  {"\
Usage: %s [--seed=INTEGER]\n\
Test how fast your machine can add, multiply and divide random numbers in\n\
fixed and floating point.\n\
\n", 704},
  {"\
  -s, --seed=INTEGER  seed for random number generator\n\
      --help          display this help and exit\n\
      --version       output version information and exit\n\
\n", 705},
  {"%s: Non-option arguments are not allowed\n", 706},
  {"\
\n\
Adding random numbers...", 707},
  {"  Fixed: %d", 708},
  {"  Float: %d", 709},
  {"\
\n\
Multiplying random numbers...", 710},
  {"\
\n\
Dividing random numbers...", 711},
  {"%s: You must use `--min=BRIGHTNESS'\n", 712},
  {"\
Usage: %s --min=BRIGHTNESS <INPUT.ppm >OUTPUT.ppm\n\
Read a PPM-format picture from standard input and convert all dark pixels\n\
to R=0,G=0,B=1 which ppmtodumb recognizes as meaning transparent.  Write \
the\n\
resulting image to standard output.\n\
\n", 713},
  {"\
  -m, --min=BRIGHTNESS  If a pixel is darker than BRIGHTNESS, it is made\n\
                        transparent.  BRIGHTNESS must be an integer.\n\
                        Its range depends on the input data.\n\
      --help            Display this help and exit.\n\
      --version         Output version information and exit.\n\
\n", 714},
  {"%s: integer `%s' should be between %ld and %ld\n", 715},
  {"trouble with XGetImage\n", 716},
  {"\
Usage: %s [OPTION]... --character=C >OUTPUT.pgm\n\
Converts one glyph of an X font to PGM format and outputs it on stdout.\n\
\n", 717},
  {"\
  -f, --font=FONT  Use X font FONT, which should be quoted to protect\n\
                   it from the shell.  The default is\n\
                   \
\"-bitstream-charter-bold-r-*-*-60-*-*-*-*-*-iso8859-1\".\n\
  -a, --anti-alias=FACTOR\n\
                   Shrink the bitmap by this factor before saving it.  This\n\
                   results in FACTOR-1 gray levels between black and white.\n\
                   FACTOR must be a positive integer.\n\
  -d, --display=DISPLAY\n\
                   Connect to X server DISPLAY.\n\
  -c, --character=C\n\
                   The character to convert.\n\
      --help       Display this help and exit.\n\
      --version    Output version information and exit.\n\
\n", 718},
  {"%s: Convert one character at a time.\n", 719},
  {"%s: You must use `--character=C'.\n", 720},
  {"Can't open display %s", 721},
  {"<default>", 722},
  {"%s: font `%s' does not exist\n", 723},
  {"%s: Specify only one output filename.\n", 724},
  {"%s: You must specify an output filename.\n", 725},
  {"\
Usage: %s [-m MAPNAME] -o FILENAME\n\
Creates a map consisting of just one 512x512x128 room and the player \
object.\n\
\n", 726},
  {"\
  -m, --map=MAPNAME          Name of map to save in the WAD.  Defaults to \
E1M1.\n\
  -o, --output-wad=FILENAME  Save the map in this file.\n\
      --help                 Display this help and exit.\n\
      --version              Output version information and exit.\n\
\n", 727},
  {"%s: PNAMES filename was already given\n", 728},
  {"%s: TEXTURES filename was already given\n", 729},
  {"%s: PNAMES filename was not given\n", 730},
  {"%s: TEXTURES filename was not given\n", 731},
  {"%s: too many parameters\n", 732},
  {"\
Usage: %s [-d] -p PNAMES -t TEXTURES [SOURCE]\n\
Compiles metatexture information from SOURCE to PNAMES and TEXTURES lumps\n\
used by DUMB.  SOURCE defaults to standard input.\n\
\n", 733},
  {"\
  -d, --debug                     print debugging info\n\
  -p, --output-pnames=PNAMES      write the pnames lump to the file PNAMES\n\
  -t, --output-textures=TEXTURES  write the textures lump to the file \
TEXTURES\n\
      --help                      display this help and exit\n\
      --version                   output version information and exit\n\
\n", 734},
  {"\
The input consists of entries such as the following (from \
dumb-game-0.13.1):\n", 735},
  {"%s:%d: patch with no texture (ignored)\n", 736},
  {"%s:%d: syntax error (ignoring)\n", 737},
  {"%s: %ld pnames, %d textures\n", 738},
  {"%s: invalid bytes-per-pixel value `%s'; must be 1, 2 or 4\n", 739},
  {"%s: You must specify one of the `-fpPmc' options\n", 740},
  {"%s: You may not specify more than one `-fpPmc' option\n", 741},
  {"%s: Only one bytes-per-pixel number is allowed\n", 742},
  {"\
Usage: %s [OPTION]... <INPUT.png >OUTPUT.lump\n\
Converts graphic files from the Portable Network Graphics (PNG) format\n\
to DUMB's internal formats.\n\
\n", 743},
  {"\
  -f, --flat            create a 64x64 flat-format graphic\n\
  -p, --patch           create a transparent patch\n\
  -P, --opaque-patch    create a non-transparent patch\n\
  -m, --playpal         create a playpal\n\
  -c, --colormap        create a colormap (doesn't need INPUT.png)\n\
  -M, --use-playpal=PLAYPAL\n\
                        read the playpal data from PLAYPAL\n\
                        (default: %s)\n\
      --bytes-per-pixel=NUMBER\n\
                        how many bytes per pixel: 1 (default), 2 or 4\n\
  -2                    same as --bytes-per-pixel=2\n\
  -4                    same as --bytes-per-pixel=4\n\
  -i, --id-compatible   turn on id compatibility\n\
      --help            display this help and exit\n\
      --version         output version information and exit\n\
\n", 744},
  {"%s: out of memory\n", 745},
  {"this image is the wrong size for a flat", 746},
  {"PNG library initialisation failed\n", 747},
  {"\
Usage: %s [OPTION]... <INPUT.ppm >OUTPUT.lump\n\
Converts graphic files from the portable pixmap format (PPM) to DUMB's\n\
internal formats.\n\
\n", 748},
  {"\
  -f, --flat            create a 64x64 flat-format graphic\n\
  -p, --patch           create a transparent patch\n\
  -P, --opaque-patch    create a non-transparent patch\n\
  -m, --playpal         create a playpal\n\
  -c, --colormap        create a colormap\n\
  -M, --use-playpal=PLAYPAL\n\
                        read the playpal data from PLAYPAL\n\
                        (default: %s)\n\
      --bytes-per-pixel=NUMBER\n\
                        how many bytes per pixel: 1 (default), 2 or 4\n\
  -2                    same as --bytes-per-pixel=2\n\
  -4                    same as --bytes-per-pixel=4\n\
  -i, --id-compatible   turn on id compatibility\n\
      --help            display this help and exit\n\
      --version         output version information and exit\n\
\n", 749},
  {"bad ppm", 750},
  {"this ppm is the wrong size for a flat", 751},
  {"\
Usage: %s [OPTION FILE [FILE]...]...\n\
Extract, copy and concatenate WAD files.\n\
\n", 752},
  {"\
  -r, --read-iwad=FILE               read this file as an IWAD\n\
  -p, --read-pwad=FILE [FILE]...     read these files as PWADs\n\
  -w, --output-pwad=FILE             start writing output to this PWAD\n\
  -W, --output-iwad=FILE             start writing output to this IWAD\n\
  -D, --output-directory=DIRECTORY   start writing output to this directory\n\
  -c, --copy-wad=FILE [FILE]...      copy all lumps in these wadfiles\n\
                                     (without patching)\n\
  -l, --copy-lump=LUMP [LUMP]...     copy these lumps to the current wad\n\
  -L, --empty-lump=LUMP [LUMP]...    spit out an empty lump\n\
  -x, --extract-lump=LUMP [LUMP]...  copy these lumps to raw files\n\
  -f, --read-lump=FILE [FILE]...     copy raw files to lumps\n\
                                     (guessing lump names)\n\
  -F, --append-lump=FILE [FILE]...   copy raw files to lump\n\
                                     (adding to current)\n\
  -n, --rename-lump OLD NEW          copy lump OLD to lump NEW\n\
      --help                         display this help and exit\n\
      --version                      output version information and exit\n\
\n", 753},
  {"\
Usage:  wadtool <option> <file> <file>... <option> <file>...\n\
\n\
Options:\n\
 -r <wadfile> : read this file as an IWAD\n\
 -p <wadfile> : read these files as PWADs\n\
 -w <wadfile> : start writing output to this PWAD\n\
 -W <wadfile> : start writing output to this IWAD\n\
 -D <dir>     : start writing output to this directory\n\
 -c <wadfile> : copy all lumps in this wadfile (without patching)\n\
 -l <lump>    : copy these lumps to the current wad\n\
 -L <lump>    : spit out an empty lump\n\
 -x <lump>    : copy these lumps to raw files\n\
 -f <rawfile> : copy raw file to lump (guessing lumpname)\n\
 -F <rawfile> : copy raw file to lump (adding to current)\n\
 -n <s> <d>   : copy lump 's' to lump 'd'\n\
\n", 754},
  {"copying %s(%s) -> %s(%s)\n", 755},
  {"Output WAD not chosen", 756},
  {"copying %s -> %s(%s)", 757},
  {"Lump `%s' not found", 758},
  {"copying %s(%s) -> %s(%s)", 759},
  {"Not enough arguments", 760},
  {"You must select exactly two lines.", 761},
  {"Lines don't cross.", 762},
  {"first vertex is %d, angle %f", 763},
  {"  vertex %d, angle is %f", 764},
  {"connecting %d -> %d", 765},
  {"%d and %d are already connected", 766},
  {"No vertices were connected.", 767},
  {"Some vertices were not connected.", 768},
  {"There must be exactly two lines connected to the selected vertex.", 769},
  {"You must select two one-sided sector boundaries.", 770},
  {"Sector does not seem corridor-like.", 771},
  {"No Create function for this mode yet!", 772},
  {"Flat Texture Browser", 773},
  {"Wall Texture Browser", 774},
  {"Sprite Texture Browser", 775},
  {"Patch Texture Browser", 776},
  {"OK!", 777},
  {"Cancel", 778},
  {"Preview", 779},
  {"Out of memory in XInternalConnectionNumbers", 780},
  {"RotState:", 781},
  {"Rotate", 782},
  {"Advance", 783},
  {"Phase:", 784},
  {"Animate", 785},
  {"Sprite:", 786},
  {"SpriteSize:", 787},
  {"Init", 788},
  {"Detect", 789},
  {"Fight", 790},
  {"Special", 791},
  {"Ouch", 792},
  {"Die", 793},
  {"Explode", 794},
  {"ID:", 795},
  {"%s: internal limit on wad files exceeded\n", 796},
  {"\
Usage: %s [OPTION]... [WADFILE]...\n\
Interactively view ProtoThings in X11.\n\
\n", 797},
  {"\
  -w, --load-wad=FILE    load FILE as a WAD.  WADFILE argument does the \
same.\n\
  -s, --no-sound         don't try to play sounds\n\
  -d, --display=DISPLAY  use X display DISPLAY\n\
  -l, --log-to=FILE      save messages to FILE\n\
  -v, --verbose          log to the screen\n\
      --help             display this help and exit\n\
      --version          output version information and exit\n\
\n", 798},
  {"\
If no WADFILE nor --load-wad=FILE arguments are given, XProtoThing\n\
loads `doom2.wad'.\n\
\n", 799},
  {"no PROTOS lump in wad", 800},
  {"no protos", 801},
  {"Level Saved.", 802},
  {"\
Usage: %s [OPTION]... [WADFILE]...\n\
Interactively edit DUMB levels in X11.\n\
\n", 803},
  {"\
  -w, --load-wad=FILE    load FILE as a WAD.  WADFILE argument does the \
same.\n\
  -m, --map=MAPNAME      start editing map MAPNAME (default E1M1)\n\
  -d, --display=DISPLAY  use X display DISPLAY\n\
  -l, --log-to=FILE      save messages to FILE\n\
  -v, --verbose          log to the screen\n\
      --help             display this help and exit\n\
      --version          output version information and exit\n\
\n", 804},
  {"\
If no WADFILE nor --load-wad=FILE arguments are given, XWad loads\n\
`doom.wad' if the map name begins with `E' and `doom2.wad' otherwise.\n\
\n", 805},
  {"BigMap", 806},
  {"VerMode", 807},
  {"Load:", 808},
  {"LineMode", 809},
  {"Save As:", 810},
  {"SectMode", 811},
  {"Prev", 812},
  {"Next", 813},
  {"ThingMode", 814},
  {"Grid:", 815},
  {"Sprites", 816},
  {"Zoom In", 817},
  {"Zoom Out", 818},
  {"Scale:", 819},
  {"Vertex #", 820},
  {"X-coord", 821},
  {"Y-coord", 822},
  {"Connect", 823},
  {"CCW", 824},
  {"JoinLines", 825},
  {"Sect #", 826},
  {"FloorLvl", 827},
  {"CeilingLvl", 828},
  {"Floor", 829},
  {"Ceiling", 830},
  {"Light", 831},
  {"Type", 832},
  {"Tag", 833},
  {"Stairs", 834},
  {"BigStairs", 835},
  {"Thing #", 836},
  {"Easy", 837},
  {"Delete", 838},
  {"Medium", 839},
  {"Multi", 840},
  {"Hard", 841},
  {"Deaf", 842},
  {"Angle", 843},
  {"Line #", 844},
  {"VerFlip", 845},
  {"SideFlip", 846},
  {"Impassible", 847},
  {"TwoSided", 848},
  {"M-Impass", 849},
  {"UnpUpper", 850},
  {"UnpLower", 851},
  {"Secret", 852},
  {"BlockSnd", 853},
  {"NoMap", 854},
  {"ForceMap", 855},
  {"Poster", 856},
  {"Crossing", 857},
  {"Split", 858},
  {"MkSector", 859},
  {"Corridor", 860},
  {"Side #", 861},
  {"Sector #", 862},
  {"Offset", 863},
  {"Texture", 864},
  {"U-Texture", 865},
  {"L-Texture", 866},
};

int _msg_tbl_length = 866;
