/* Automatically generated by po2tbl.sed from dumb.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"ticks to pass before key autorelease or 0", 2},
  {"ticks to pass before shift autorelease or 0", 3},
  {"aalib_input must be initialised after aalib_video", 4},
  {"AA-lib keyboard driver supports AA_SENDRELEASE", 5},
  {"AA-lib keyboard driver doesn't support AA_SENDRELEASE", 6},
  {"very fast (but not as perfect)", 7},
  {"<disabled at compile time>", 8},
  {"brightness (0-255)", 9},
  {"contrast (0-255)", 10},
  {"gamma (1000 corresponds to 1.0)", 11},
  {"multiply factor for dim color (ditto)", 12},
  {"multiply factor for bold color (ditto)", 13},
  {"dithering type", 14},
  {"range of random value to add to each pixel (0-inf)", 15},
  {"invert the whole screen", 16},
  {"name of the font you use", 17},
  {"use the normal attribute", 18},
  {"use the bold (double bright) attribute", 19},
  {"use the boldfont attribute", 20},
  {"use the dim (half bright) attribute", 21},
  {"use the reverse attribute", 22},
  {"use all 256 characters", 23},
  {"use eight-bit ASCII", 24},
  {"AA-lib initialisation failed", 25},
  {"AA-lib doesn't know of font `%s'", 26},
  {"The following fonts are available:", 27},
  {"Bad AnimTexNum (%d)", 28},
  {"too many banners", 29},
  {"init banner %d", 30},
  {"Quit", 31},
  {"Move forward", 32},
  {"Move backward", 33},
  {"Turn left", 34},
  {"Turn right", 35},
  {"Turn around", 36},
  {"Sidestep left", 37},
  {"Sidestep right", 38},
  {"Jump / Swim/Fly up", 39},
  {"Duck / Swim/Fly down", 40},
  {"Look up", 41},
  {"Look down", 42},
  {"Aim up", 43},
  {"Aim down", 44},
  {"Center view", 45},
  {"Run", 46},
  {"Strafe", 47},
  {"Activate", 48},
  {"Shoot", 49},
  {"Shoot special", 50},
  {"Select next weapon", 51},
  {"Select previous weapon", 52},
  {"Select weapon 0", 53},
  {"Select weapon 1", 54},
  {"Select weapon 2", 55},
  {"Select weapon 3", 56},
  {"Select weapon 4", 57},
  {"Select weapon 5", 58},
  {"Select weapon 6", 59},
  {"Select weapon 7", 60},
  {"Select weapon 8", 61},
  {"Select weapon 9", 62},
  {"Use item", 63},
  {"Next item", 64},
  {"Previous item", 65},
  {"disable mouse support", 66},
  {"mouse sensitivity x-axis (4)", 67},
  {"mouse sensitivity y-axis (2)", 68},
  {"Can't initialize mouse! Missing driver?", 69},
  {"dont try to use page flipping", 70},
  {"use VESA 2.0 linear modes (UniVBE preferred)", 71},
  {"Can't initialize video: %s", 72},
  {"Using page flipping", 73},
  {"Using double buffering", 74},
  {"Using two-stage double buffering", 75},
  {"Video mode: %s (%s)", 76},
  {"got SIGALRM: renderer must have gotten stuck...", 77},
  {"save configuration after every run", 78},
  {"save configuration this time only", 79},
  {"specify wadfiles to load", 80},
  {"directories in which to look for wads", 81},
  {"filename of doom.wad", 82},
  {"filename of doom2.wad", 83},
  {"filename of doom4dum.wad", 84},
  {"set starting map", 85},
  {"don't log to the screen", 86},
  {"don't create any objects, just preview the map", 87},
  {"set difficulty level", 88},
  {"disable sound", 89},
  {"video width", 90},
  {"video height", 91},
  {"video depth (in bytes/pixel)", 92},
  {"log to this file", 93},
  {"record player actions to file", 94},
  {"playback player actions from file", 95},
  {"hide gettables and banners", 96},
  {"show a crosshair in the center of the view", 97},
  {"multiply the pixels x size", 98},
  {"multiply the pixels y size", 99},
  {"skip pixels when multiplying x size", 100},
  {"skip pixels when multiplying y size", 101},
  {"load textures before game starts", 102},
  {"angle from forward of player view", 103},
  {"offset from center of player view", 104},
  {"network play: slave mode", 105},
  {"network play: master mode", 106},
  {"force single player mode", 107},
  {"angle to rotate view by", 108},
  {"maximum frames to render", 109},
  {"enable 3rd person perspective", 110},
  {"Input Driver", 111},
  {"Video Driver", 112},
  {"Sound Driver", 113},
  {"Network Driver", 114},
  {"Network Play", 115},
  {"General Game Control", 116},
  {"Player Interface", 117},
  {"Keyboard Mapping", 118},
  {"\
This program is free software; you may redistribute it under the terms of\n\
the GNU General Public License.  This program has absolutely no warranty.\n", 119},
  {"Preloading wall textures", 120},
  {"Preloading floor/ceiling textures", 121},
  {"Preloading sprites", 122},
  {"\
This program was compiled to use MMX, but your processor\n\
does not appear to support it.\n", 123},
  {"Read configuration from %s", 124},
  {"network mode: slave", 125},
  {"network mode: master", 126},
  {"Unsupported BPP=%d", 127},
  {"Can't find sector for player", 128},
  {"starting game", 129},
  {"Demo ran out...", 130},
  {"saving snapshot...", 131},
  {"snapshot done", 132},
  {"%d ticks passed with MAXTICKS=%d", 133},
  {"WARNING: this system is running faster than the timer resolution", 134},
  {"Try running DUMB in a larger window.", 135},
  {"YOU DIED.  TOO BAD...", 136},
  {"%d frames, %d seconds, %f fps", 137},
  {"Saving config to %s", 138},
  {"dummy input: always quit", 139},
  {"processor timing overcompensation tweak", 140},
  {"forward speed", 141},
  {"strafe speed", 142},
  {"turning speed", 143},
  {"jumping speed", 144},
  {"PLAYER %d WARPED", 145},
  {"PLAYER %d CHEATED", 146},
  {"PLAYER %d WIBBLED LOUDLY", 147},
  {"PLAYER %d RETURNED", 148},
  {"PLAYER %d SMASHES PUMPKINS", 149},
  {"Strange gettable type=%d num=%d", 150},
  {"YOU GOT THE %s!", 151},
  {"THAT %s WOULD BE WASTED...", 152},
  {"GOT A %s.", 153},
  {"init %d gettables", 154},
  {"GGI: ggiInit failed.", 155},
  {"GGI: ggiOpen failed.", 156},
  {"Bad BPP (%d) in init_video", 157},
  {"Depth %d not supported.", 158},
  {"Mode not supported by LibGGI.", 159},
  {"init_video in copying mode pagelen=%d", 160},
  {"NULL keyname for keycode 0x%08lX", 161},
  {"No action for keyname \"%s\"", 162},
  {"--- begin keymap debug dump", 163},
  {"--- end keymap debug dump", 164},
  {"attempt to resize keymap under its length", 165},
  {"Keys to quit DUMB", 166},
  {"Keys to move forward", 167},
  {"Keys to move backward", 168},
  {"Keys to turn left", 169},
  {"Keys to turn right", 170},
  {"(not implemented)", 171},
  {"Keys to sidestep left", 172},
  {"Keys to sidestep right", 173},
  {"Keys to jump / swim/fly up", 174},
  {"Keys to duck / swim/fly down", 175},
  {"Keys to look up", 176},
  {"Keys to look down", 177},
  {"Keys to aim up", 178},
  {"Keys to aim down", 179},
  {"Keys to look straight ahead", 180},
  {"Keys to hold to move faster", 181},
  {"Keys to hold to sidestep instead of turning", 182},
  {"Keys to activate switches and doors", 183},
  {"Keys to shoot with the selected weapon", 184},
  {"Keys to select the next weapon", 185},
  {"Keys to select the previous weapon", 186},
  {"Keys to select weapon 0", 187},
  {"Keys to select weapon 1", 188},
  {"Keys to select weapon 2", 189},
  {"Keys to select weapon 3", 190},
  {"Keys to select weapon 4", 191},
  {"Keys to select weapon 5", 192},
  {"Keys to select weapon 6", 193},
  {"Keys to select weapon 7", 194},
  {"Keys to select weapon 8", 195},
  {"Keys to select weapon 9", 196},
  {"Keys to use the selected item", 197},
  {"Keys to select the next item", 198},
  {"Keys to select the previous item", 199},
  {"Keymap is empty, installing defaults.", 200},
  {"Loading %s: difficulty=%d", 201},
  {"Loading %s grain=%d align=%d", 202},
  {"levdata: %s will not be aligned correctly", 203},
  {"Init %d %s", 204},
  {"Uh-oh: no player!", 205},
  {"Freeing level data for %s", 206},
  {"Pre-freeing %s for %s", 207},
  {"bad maplumptype (%d) in apply_update()", 208},
  {"no decode func for maplumptype %d", 209},
  {"out of range item (%d) in apply_update()", 210},
  {"got plinfo_update for player with no plinfo?", 211},
  {"Ran out of thing slots", 212},
  {"Couldn't find protothing ID=%d", 213},
  {"diffchk: strange difficulty??? (%d)", 214},
  {"warning: no LEVINFO lump for this game", 215},
  {"Init %d levels", 216},
  {"bogus levinfo pointer in levinfo_load", 217},
  {"no levinfo for %s, so can't find next level", 218},
  {"Loaded %d linetypes, of which %d scrolling", 219},
  {"Failed to find LINETYPE in wad", 220},
  {"Loaded %d sectortypes", 221},
  {"Failed to find SECTTYPE in wad", 222},
  {"mouse type", 223},
  {"mouse device", 224},
  {"Console open failed", 225},
  {"Console in raw mode", 226},
  {"maximum pages to use for flipping", 227},
  {"minimum pages to use for flipping", 228},
  {"No linear framebuf? Try running as root (not just suid root)", 229},
  {"Too little video RAM, or no linear fb: linearlen=%d pagelen=%d", 230},
  {"init_video in copying mode linearlen=%d pagelen=%d npages=%d", 231},
  {"init_video in flipping mode linearlen=%d pagelen=%d npages=%d", 232},
  {"too many stations", 233},
  {"network driver doesn't know how to gethostname()?", 234},
  {"packet length not a multiple of 4 (type=%c len=%lu)", 235},
  {"msec to wait for slaves to init", 236},
  {"msec to wait for slaves to catch up", 237},
  {"msec to wait for master", 238},
  {"msec to allow slaves to get behind", 239},
  {"run network asychronously", 240},
  {"time between sending acks", 241},
  {"sending slave-init to %s (station %d)", 242},
  {"sending slave-init packets...", 243},
  {"waiting for slaves to initialise", 244},
  {"all slaves up", 245},
  {"sending init-request", 246},
  {"waiting for slave init info from master", 247},
  {"waiting for slave '%s' (%d) to catch up", 248},
  {"slave '%s' (%d) seems to be dead", 249},
  {"inconsistent packet length %lu > %lu", 250},
  {"init request from %s ignored", 251},
  {"got init request: setting up new station %d", 252},
  {"init pkt length mismatch: got %d, expecting %lu", 253},
  {"protocol version mismatch: got %d, expecting %d", 254},
  {"strange packet type (%c) in netplay_poll()", 255},
  {"station %s (%d) lives!", 256},
  {"start=%d end=%d", 257},
  {"problems with fb coords in draw_wall_segment", 258},
  {"problems with fb coords in draw_sky_segment", 259},
  {"problems with fb coords in draw_obj", 260},
  {"Column (%d) off edge of sprite (width=%d)", 261},
  {"init_renderer fb dimensions (%d,%d) view (%d,%d) bpp=%d", 262},
  {"fb1=%d fb2=%d for wall %d", 263},
  {"Too many wall start_events column=%d", 264},
  {"Too many obj start_events", 265},
  {"active_count=%d at rw_column %d", 266},
  {"active_obj_count=%d at rw_column %d", 267},
  {"Too many active objects (%d)", 268},
  {"unimplemented LT_TermType %d", 269},
  {"find_spot: found %d", 270},
  {"find_spot: no spot found", 271},
  {"boss tag effect on sector %d", 272},
  {"strange WallHitType (%d) in thing_hit_wall()", 273},
  {"player is not allowed to activate type %d", 274},
  {"non-player is not allowed to activate type %d", 275},
  {"YOU NEED A KEY!", 276},
  {"line %d is having something done to it by thing %d", 277},
  {"tried manual action on wall with no back?", 278},
  {"tried manual_f action on wall with no front?", 279},
  {"strange lumptype (%d) while performing actions", 280},
  {"Obj %d is heatseeking %d", 281},
  {"thing %d is out to get %d!", 282},
  {"thing %d took %d damage (%d/%d hits)", 283},
  {"melee: %d's attack on %d failed", 284},
  {"Thing %d becomes type %d; old type was %d", 285},
  {"UDP port to listen on", 286},
  {"IP broadcast address", 287},
  {"Host-specific port numbers will be ignored when broadcasting", 288},
  {"Invalid port number `%s' -- assuming %d", 289},
  {"gethostbyname() failed for '%s': errno=%d", 290},
  {"error (%d) in recvfrom sock=%d", 291},
  {"data from new station (%08x)", 292},
  {"error %d blocking UDP socket", 293},
  {"error (%d) in peek recvfrom sock=%d", 294},
  {"error %d unblocking UDP socket", 295},
  {"error (%d) in sendto sock=%d", 296},
  {"error (%d) in broadcast sendto sock=%d", 297},
  {"error %d creating UDP socket", 298},
  {"error %d binding UDP socket", 299},
  {"udp: broadcast access denied (try running as root)", 300},
  {"udp broadcast: %d packets, %d bytes, avg len %d", 301},
  {"udp unicast:   %d packets, %d bytes, avg len %d", 302},
  {"udp total:     %d packets, %d bytes, avg len %d", 303},
  {"copying ceiling texture from %d to %d", 304},
  {"copying floor texture from %d to %d", 305},
  {"sector event terminated OK s=%d type=%d", 306},
  {"do_sector_event: strange eventtype (%d)", 307},
  {"sector %d has no center?", 308},
  {"do_thing_event: teleporting %d", 309},
  {"do_thing_event: strange eventtype (%d)", 310},
  {"do_side_event: switching %d on", 311},
  {"do_side_event: switching %d off", 312},
  {"do_side_event: strange eventtype (%d)", 313},
  {"No free event in insert_event(%d,%d,%d)", 314},
  {"event %d passed its stop date", 315},
  {"event %d entering stage %d entity %d", 316},
  {"Strange lumptype %d in um_events", 317},
  {"%d is being crushed, but not by sector %d ???", 318},
  {"climbing, factor=%d", 319},
  {"VGA-linear=%x", 320},
  {"GL-flipmode=%d", 321},
  {"allow use of XFree86's DGA extension", 322},
  {"allow use of the MIT shared memory extension", 323},
  {"synchronous I/O (for debugging)", 324},
  {"dump core on X errors (for debugging)", 325},
  {"allow use of the XKeyboard extension", 326},
  {"grab the keyboard focus while DUMB runs", 327},
  {"Shm Attaches=%d", 328},
  {"x11_video: Can't open default display", 329},
  {"DGA viewport=%d,%d,%d", 330},
  {"X server doesn't support DGA", 331},
  {"using XF86-DGA", 332},
  {"XCreateWindow failed", 333},
  {"win-id=%ld", 334},
  {"XShmCreateImage failed", 335},
  {"shmget failed", 336},
  {"XShm disabled: are we not local?", 337},
  {"using XShm", 338},
  {"XCreateImage failed", 339},
  {"using Xlib Images (slow)", 340},
  {"X colormap came back as None.  Probably some strange visual.", 341},
  {"cmap-id=%ld", 342},
  {"Installing colormap", 343},
  {"Got XEvent", 344},
  {"Got some weird event type: %d", 345},
  {"Got KeyPress", 346},
  {"Got KeyRelease", 347},
  {"EnterNotify received\n", 348},
  {"LeaveNotify received\n", 349},
  {"x11_input must be initialised after x11_video", 350},
  {"XKB %d.%d in Xlib is incompatible with our %d.%d", 351},
  {"XKB %d.%d in X server is incompatible with our %d.%d", 352},
  {"X server does not support DetectableAutorepeat", 353},
  {"DetectableAutorepeat enabled via XKB", 354},
  {"keyboard grab failed!", 355},
  {"Couldn't initialize sound: %s", 356},
  {"Sound driver: %s (%s)", 357},
  {"couldn't find SOUNDS lump", 358},
  {"Loaded %d sounds", 359},
  {"play_dsound got bad sound id (%d)", 360},
  {"Sound device file to open", 361},
  {"Maximum allowed bits per channel", 362},
  {"Force monaural sound", 363},
  {"init_sound: fd=%d fragsize=%d (%d bytes)", 364},
  {"init_sound: speed=%d window=%d (%f seconds) slush=%d", 365},
  {"init_sound: can't get sound format list: %s", 366},
  {"init_sound: no supported formats found", 367},
  {"init_sound: set format failed: %s", 368},
  {"init_sound: driver changed the format to something we don't support", 369},
  {"init_sound: set stereo failed: %s", 370},
  {"init_sound: mono not available, using stereo", 371},
  {"init_sound: stereo not available, using mono", 372},
  {"init_sound: set fragsize failed: %s", 373},
  {"init_sound: set speed failed: %s", 374},
  {"init_sound: sample rate %d Hz not available, using %d Hz", 375},
  {"poll_sound: underrun detected", 376},
  {"Bits per channel", 377},
  {"Stereo sound instead of mono", 378},
  {"init_sound: no sounddevice present", 379},
  {"Failed to allocate PCMWAVEFORMAT struct", 380},
  {"waveOutOpen failed - status = %d\n", 381},
  {"Failed to allocate WAVEHDR struct", 382},
  {"Failed to allocate shared audio buffer", 383},
  {"init_sound: mme_handle=%d fragsize=%d (%ld bytes)", 384},
  {"init_sound: speed=%d slush=%d", 385},
  {"waveOutWrite failed", 386},
  {"wanted rot %c for sprite %s phase %d???", 387},
  {"Can't find sprite %s, ph=%d (%c) rot=%c", 388},
  {"Can't find ThingPhase id=%d", 389},
  {"sndmix_sample_size: strange format %d", 390},
  {"sndmix_play_sound: out of slots (sound discarded)", 391},
  {"sndmix_calc_frag: strange format %d", 392},
  {"Bad BPP value in paste_pict", 393},
  {"Bad BPP value in paste_jpatch", 394},
  {"npnames=%d (should be %d)", 395},
  {"No metatexture lumps in WAD", 396},
  {"%s has %d wall textures", 397},
  {"Can't find any sprites in WAD", 398},
  {"too short sprite: %s", 399},
  {"Init %d sprites", 400},
  {"Bad lumpnum for texture %s in load_sprite()", 401},
  {"Can't find sprite texture %s", 402},
  {"Can't find any flats in WAD", 403},
  {"funny length (%d) for flat %s", 404},
  {"Init %d flats", 405},
  {"Can't find flat texture %s", 406},
  {"Patchnum %d (%s) doesn't exist", 407},
  {"loading patchnum %d (%s)", 408},
  {"init_walltexs(): %d textures", 409},
  {"Can't find wall texture %s", 410},
  {"wtex \"%s\" is unaligned with offset %ld!", 411},
  {"using one-patch kludge for %s", 412},
  {"load_walltex %s at %d bpp", 413},
  {"%s: %d patches", 414},
  {"Can't make sense of patch #%d, texture %s", 415},
  {"%s: loaded", 416},
  {"found font %s already loaded", 417},
  {"Too many fonts", 418},
  {"Loading font #%d (%s)", 419},
  {"Request for bad fontnum (%d)", 420},
  {"Request for bad font char (%d:%d)", 421},
  {"too many misc textures", 422},
  {"get_texture_num: unsupported texture type (%d)", 423},
  {"get_texture_bynum: unsupported texture type (%d)", 424},
  {"count_textures: unsupported texture type (%d)", 425},
  {"init_textures(): done", 426},
  {"Strange texture type (0x%x) in free_texels", 427},
  {"Strange BPP value (%d) in load_texels", 428},
  {"Strange texture type (0x%x) in load_texels", 429},
  {"Report bugs to <%s>.\n", 430},
  {"`%s' is not an option.  I'll use `%s' instead.\n", 431},
  {"switch requires an argument -- %s\n", 432},
  {"internal error: set_conf(): strange type %d\n", 433},
  {"\
; %s\n\
; this file was created automatically, but you can modify it if you want\n", 434},
  {"\
\n\
; Module `%s': %s\n", 435},
  {"internal error: save_conf(): strange type %d, treating as int\n", 436},
  {"Missing quote in configuration file\n", 437},
  {"Trailing backslash in configuration file\n", 438},
  {"`%s' is not a switch I recognise\n", 439},
  {"\
I don't understand your command line.  The token which is causing trouble\n\
is `%s'.\n\
\n", 440},
  {"\
usage: %s [switch [parameter]] [switch [parameter]]...\n\
\n\
For a list of all switches available, invoke %s --help all\n\
\n\
Or, for switches relating to a particular module, %s --help <module>\n\
where module is one of: all", 441},
  {"\
\n\
\n\
For information on a particular switch: %s --help <switch>\n\
\n", 442},
  {"\
You can abbreviate `--help' as `-\\?'.\n\
\n", 443},
  {"Module `%s': %s\n", 444},
  {"<no configurable items>\n", 445},
  {" <integer>", 446},
  {" <enum>", 447},
  {" <string>", 448},
  {" <list>", 449},
  {" <internal error: strange type %d>", 450},
  {" (short form -%c)", 451},
  {"\
Help for %s:\n\
  `%s'\n", 452},
  {"  Type=%s\n", 453},
  {"Integer", 454},
  {"  Default=%d\n", 455},
  {"Boolean", 456},
  {"Enumerated", 457},
  {"  Default=%s\n", 458},
  {"  Values=", 459},
  {"String", 460},
  {"List", 461},
  {"  Type=%d (internal error)\n", 462},
  {"  Short Form=-%c\n", 463},
  {"  Maxlen=%d\n", 464},
  {"  Cannot be saved in a config file.\n", 465},
  {"Copyright (C) %s %s\n", 466},
  {"%s: opening log file: %s", 467},
  {"Normal exit.", 468},
  {"%d errors occured.", 469},
  {"A fatal error occured.", 470},
  {"System error message (may be unrelated)", 471},
  {"%s: mmap %lu bytes: %s", 472},
  {"mmap %lu bytes: %s", 473},
  {"%s: munmapping %lu bytes: %s", 474},
  {"%s: seeking to %u: %s", 475},
  {"%s: short read (%lu<%lu): %s", 476},
  {"%s: short read (%d<%lu): %s", 477},
  {"%s: opening: %s", 478},
  {"%s: closing: %s", 479},
  {"mmapping %lu zero bytes: %s", 480},
  {"%s: mmapping %lu bytes: %s", 481},
  {"munmapping %lu bytes @ %p: %s", 482},
  {"out of memory reallocating %lu bytes (old=%p)", 483},
  {"out of memory allocating %lu bytes", 484},
  {"Attempt to free NULL.", 485},
  {"Bad lumpnum in load_lump", 486},
  {"a lump", 487},
  {"Bad lumpnum in free_lump", 488},
  {"wad hashtable: %d entries unused, max chain %d", 489},
  {"%s: lump %d has no name", 490},
  {"%s: lump %d is too big for wad", 491},
  {"%s is too short to be a valid wadfile", 492},
  {"%s mapped at %p (%lu bytes)", 493},
  {"Bad signature on %s: expecting %s, got %.4s", 494},
  {"directory for %s would be beyond end of file", 495},
  {"%s %s: %d lumps dir @ %d", 496},
  {"Can't find lump marker %s (lump %s)", 497},
  {"Can't find lump %s:%s", 498},
  {"Can't find lump %s", 499},
  {"Can't find end-marker %s", 500},
  {"End-marker %s occurs before lump %s", 501},
  {"Bad lumpnum (%x) in get_lump_*", 502},
  {"%s: can't open: %s", 503},
  {"%s: short write: %s", 504},
  {"%s: can't rewind: %s", 505},
  {"%s: can't get position: %s", 506},
  {"%s: can't align: %s", 507},
  {"deleting sector %u which has sides", 508},
  {"sector deleted under thing %d", 509},
  {"Saving level %s to %s", 510},
  {"%s: option `%s' is ambiguous\n", 511},
  {"%s: option `--%s' doesn't allow an argument\n", 512},
  {"%s: option `%c%s' doesn't allow an argument\n", 513},
  {"%s: option `%s' requires an argument\n", 514},
  {"%s: unrecognized option `--%s'\n", 515},
  {"%s: unrecognized option `%c%s'\n", 516},
  {"%s: illegal option -- %c\n", 517},
  {"%s: invalid option -- %c\n", 518},
  {"%s: option requires an argument -- %c\n", 519},
  {"%s: option `-W %s' is ambiguous\n", 520},
  {"%s: option `-W %s' doesn't allow an argument\n", 521},
  {"name expected after AnimTex", 522},
  {"To must exceed Parm", 523},
  {"Tag must come before any Texture", 524},
  {"%5d animtexes\n", 525},
  {"name expected after Gettable", 526},
  {"%5d gettables\n", 527},
  {"gettable name parameter expected", 528},
  {"gettable name unrecognised", 529},
  {"name expected after Level", 530},
  {"%5d levinfos\n", 531},
  {"unrecognised levelname: %s\n", 532},
  {"name expected after Line/SectorType", 533},
  {"ID expected after Line/SectorType", 534},
  {"ID %d (%s) not unique (clashes with %s)\n", 535},
  {"too many actions", 536},
  {"lumptype expected after Action", 537},
  {"eventtype expected after Action", 538},
  {"%5d linetypes\n", 539},
  {"%5d sectortypes\n", 540},
  {"termtype parameter expected", 541},
  {"strange lumptype", 542},
  {"strange eventtype", 543},
  {"eventtype expected after WaitFor", 544},
  {"string parameter expected", 545},
  {"character parameter expected", 546},
  {"integer parameter expected", 547},
  {"floating-point parameter expected", 548},
  {"time parameter expected", 549},
  {"speed parameter expected", 550},
  {"arc parameter expected", 551},
  {"strange timing unit", 552},
  {"strange speed unit", 553},
  {"strange arc unit", 554},
  {"name expected after PhaseTable", 555},
  {"%5d phase tables\n", 556},
  {"phase table name parameter expected", 557},
  {"phase table name unrecognised", 558},
  {"you need to specify a phasetable first", 559},
  {"phase name parameter expected", 560},
  {"phase name unrecognised", 561},
  {"name expected after Proto", 562},
  {"%5d protos: sorting", 563},
  {", writing", 564},
  {"warning: proto %s (%d) has no phasetable\n", 565},
  {"proto name parameter expected", 566},
  {"proto name unrecognised", 567},
  {"ID %d not unique (clashes with %s)\n", 568},
  {"\
Usage: %s -d DIRECTORY\n\
Compile .pt files to various lumps used by DUMB.  Ptcomp reads .pt source\n\
from standard input, and creates the following files in DIRECTORY:\n\
PHASES.lump, PROTOS.lump, GETTABLE.lump, LINETYPE.lump, SECTTYPE.lump,\n\
SOUNDS.lump, ANIMTEX.lump and LEVINFO.lump.\n\
\n", 569},
  {"\
  -d, --output-directory=DIRECTORY  write the output files to DIRECTORY\n\
      --help                        display this help and exit\n\
      --version                     output version information and exit\n\
\n", 570},
  {"%s: Deprecated usage.  Assuming you meant:\n", 571},
  {"Try `%s --help' for more information.\n", 572},
  {"%s: You must use `-o DIRECTORY'\n", 573},
  {"stdin", 574},
  {"%s: compiling...\n", 575},
  {"%s: writing...\n", 576},
  {"name expected after SoundType", 577},
  {"too many sound redirects", 578},
  {"%5d sounds\n", 579},
  {"sound name parameter expected", 580},
  {"soundtype redefined", 581},
  {"syntax error near token `%s'\n", 582},
  {"fatal error\n", 583},
  {"%s: invalid integer `%s'\n", 584},
  {"%s: integer `%s' is too large\n", 585},
  {"\
Usage: %s [--seed=INTEGER]\n\
Test how fast your machine can add, multiply and divide random numbers in\n\
fixed and floating point.\n\
\n", 586},
  {"\
  -s, --seed=INTEGER  seed for random number generator\n\
      --help          display this help and exit\n\
      --version       output version information and exit\n\
\n", 587},
  {"%s: Non-option arguments are not allowed\n", 588},
  {"\
\n\
Adding random numbers...", 589},
  {"  Fixed: %d", 590},
  {"  Float: %d", 591},
  {"\
\n\
Multiplying random numbers...", 592},
  {"\
\n\
Dividing random numbers...", 593},
  {"%s: initializing map\n", 594},
  {"%s: setting difficulty\n", 595},
  {"\
Usage: %s [OPTION]... IWAD [PWAD]...\n\
Load a map and operate on it.\n\
\n", 596},
  {"\
  Settings:\n\
  -m, --map=NAME             which map to load (default %s)\n\
      --difficulty=N         1=easy ... 5=hard (default all)\n\
      --verbose              explain what is being done\n", 597},
  {"\
  Operations:\n\
      --statistics           display statistics on the whole map\n\
      --sector-sides=SECTOR  list sides in SECTOR\n\
      --sector-things=SECTOR list things in SECTOR\n\
      --thing-sectors=THING  list sectors THING is in\n\
      --set-name=NAME        set the name of the map to NAME\n\
      --set-long-name=NAME   set the long name of the map to NAME\n\
      --output-doom=FILE     save the map to FILE in Doom format.\n\
                             .wad won't be appended automatically.\n", 598},
  {"\
  Other:\n\
      --help                 display this help and exit\n\
      --version              output version information and exit\n\
\n", 599},
  {"%s: --difficulty given twice\n", 600},
  {"%s: invalid difficulty `%s'\n", 601},
  {"%s: difficulty must be between 1 and 5\n", 602},
  {"%s: invalid sector number `%s'\n", 603},
  {"%s: invalid thing number `%s'\n", 604},
  {"%s: opening files\n", 605},
  {"%s: missing IWAD argument\n", 606},
  {"Statistics for level %s:", 607},
  {"\
\n\
\tVertices: ", 608},
  {"\
\n\
\tSectors: ", 609},
  {"\
\n\
\tSides: ", 610},
  {"\
\n\
\tLines: ", 611},
  {"\
\n\
\tThings: ", 612},
  {"%u alloced, %u inited, %u free", 613},
  {"%s: sector number %d doesn't exist\n", 614},
  {"Sides in sector %d:\n", 615},
  {"\tside %5d, line %5d\n", 616},
  {"\tside %5d, line %5d, opposite sector %5d\n", 617},
  {"Things in sector %d:", 618},
  {"%s: thing number %d doesn't exist\n", 619},
  {"Sectors thing %d is in:", 620},
  {"%s: You must use `--min=BRIGHTNESS'\n", 621},
  {"\
Usage: %s --min=BRIGHTNESS <INPUT.ppm >OUTPUT.ppm\n\
Read a PPM-format picture from standard input and convert all dark pixels\n\
to R=0,G=0,B=1 which ppmtodumb recognizes as meaning transparent.  Write \
the\n\
resulting image to standard output.\n\
\n", 622},
  {"\
  -m, --min=BRIGHTNESS  If a pixel is darker than BRIGHTNESS, it is made\n\
                        transparent.  BRIGHTNESS must be an integer.\n\
                        Its range depends on the input data.\n\
      --help            Display this help and exit.\n\
      --version         Output version information and exit.\n\
\n", 623},
  {"%s: integer `%s' should be between %ld and %ld\n", 624},
  {"trouble with XGetImage\n", 625},
  {"\
Usage: %s [OPTION]... --character=C >OUTPUT.pgm\n\
Converts one glyph of an X font to PGM format and outputs it on stdout.\n\
\n", 626},
  {"\
  -f, --font=FONT  Use X font FONT, which should be quoted to protect\n\
                   it from the shell.  The default is\n\
                   \
\"-bitstream-charter-bold-r-*-*-60-*-*-*-*-*-iso8859-1\".\n\
  -a, --anti-alias=FACTOR\n\
                   Shrink the bitmap by this factor before saving it.  This\n\
                   results in FACTOR-1 gray levels between black and white.\n\
                   FACTOR must be a positive integer.\n\
  -d, --display=DISPLAY\n\
                   Connect to X server DISPLAY.\n\
  -c, --character=C\n\
                   The character to convert.\n\
      --help       Display this help and exit.\n\
      --version    Output version information and exit.\n\
\n", 627},
  {"%s: Convert one character at a time.\n", 628},
  {"%s: You must use `--character=C'.\n", 629},
  {"Can't open display %s", 630},
  {"<default>", 631},
  {"%s: font `%s' does not exist\n", 632},
  {"%s: Specify only one output filename.\n", 633},
  {"%s: You must specify an output filename.\n", 634},
  {"\
Usage: %s [-m MAPNAME] -o FILENAME\n\
Creates a map consisting of just one 512x512x128 room and the player \
object.\n\
\n", 635},
  {"\
  -m, --map=MAPNAME          Name of map to save in the WAD.  Defaults to \
E1M1.\n\
  -o, --output-wad=FILENAME  Save the map in this file.\n\
      --help                 Display this help and exit.\n\
      --version              Output version information and exit.\n\
\n", 636},
  {"%s: PNAMES filename was already given\n", 637},
  {"%s: TEXTURES filename was already given\n", 638},
  {"%s: PNAMES filename was not given\n", 639},
  {"%s: TEXTURES filename was not given\n", 640},
  {"%s: too many parameters\n", 641},
  {"\
Usage: %s [-d] -p PNAMES -t TEXTURES [SOURCE]\n\
Compiles metatexture information from SOURCE to PNAMES and TEXTURES lumps\n\
used by DUMB.  SOURCE defaults to standard input.\n\
\n", 642},
  {"\
  -d, --debug                     print debugging info\n\
  -p, --output-pnames=PNAMES      write the pnames lump to the file PNAMES\n\
  -t, --output-textures=TEXTURES  write the textures lump to the file \
TEXTURES\n\
      --help                      display this help and exit\n\
      --version                   output version information and exit\n\
\n", 643},
  {"\
The input consists of entries such as the following (from \
dumb-game-0.13.1):\n", 644},
  {"%s:%d: patch with no texture (ignored)\n", 645},
  {"%s:%d: syntax error (ignoring)\n", 646},
  {"%s: %ld pnames, %d textures\n", 647},
  {"%s: invalid bytes-per-pixel value `%s'; must be 1, 2 or 4\n", 648},
  {"%s: You must specify one of the `-fpPmc' options\n", 649},
  {"%s: You may not specify more than one `-fpPmc' option\n", 650},
  {"%s: Only one bytes-per-pixel number is allowed\n", 651},
  {"\
Usage: %s [OPTION]... <INPUT.ppm >OUTPUT.lump\n\
Converts graphic files from the portable pixmap format (PPM) to DUMB's\n\
internal formats.\n\
\n", 652},
  {"\
  -f, --flat            create a 64x64 flat-format graphic\n\
  -p, --patch           create a transparent patch\n\
  -P, --opaque-patch    create a non-transparent patch\n\
  -m, --playpal         create a playpal\n\
  -c, --colormap        create a colormap\n\
  -M, --use-playpal=PLAYPAL\n\
                        read the playpal data from PLAYPAL\n\
                        (default: %s)\n\
      --bytes-per-pixel=NUMBER\n\
                        how many bytes per pixel: 1 (default), 2 or 4\n\
  -2                    same as --pixel-bytes=2\n\
  -4                    same as --pixel-bytes=4\n\
  -i, --id-compatible   turn on id compatibility\n\
      --help            display this help and exit\n\
      --version         output version information and exit\n\
\n", 653},
  {"%s: out of memory\n", 654},
  {"bad ppm", 655},
  {"this ppm is the wrong size for a flat", 656},
  {"\
Usage: %s [OPTION FILE [FILE]...]...\n\
Extract, copy and concatenate WAD files.\n\
\n", 657},
  {"\
  -r, --read-iwad=FILE               read this file as an IWAD\n\
  -p, --read-pwad=FILE [FILE]...     read these files as PWADs\n\
  -w, --output-pwad=FILE             start writing output to this PWAD\n\
  -W, --output-iwad=FILE             start writing output to this IWAD\n\
  -D, --output-directory=DIRECTORY   start writing output to this directory\n\
  -c, --copy-wad=FILE [FILE]...      copy all lumps in these wadfiles\n\
                                     (without patching)\n\
  -l, --copy-lump=LUMP [LUMP]...     copy these lumps to the current wad\n\
  -L, --empty-lump=LUMP [LUMP]...    spit out an empty lump\n\
  -x, --extract-lump=LUMP [LUMP]...  copy these lumps to raw files\n\
  -f, --read-lump=FILE [FILE]...     copy raw files to lumps\n\
                                     (guessing lump names)\n\
  -F, --append-lump=FILE [FILE]...   copy raw files to lump\n\
                                     (adding to current)\n\
  -n, --rename-lump OLD NEW          copy lump OLD to lump NEW\n\
      --help                         display this help and exit\n\
      --version                      output version information and exit\n\
\n", 658},
  {"\
Usage:  wadtool <option> <file> <file>... <option> <file>...\n\
\n\
Options:\n\
 -r <wadfile> : read this file as an IWAD\n\
 -p <wadfile> : read these files as PWADs\n\
 -w <wadfile> : start writing output to this PWAD\n\
 -W <wadfile> : start writing output to this IWAD\n\
 -D <dir>     : start writing output to this directory\n\
 -c <wadfile> : copy all lumps in this wadfile (without patching)\n\
 -l <lump>    : copy these lumps to the current wad\n\
 -L <lump>    : spit out an empty lump\n\
 -x <lump>    : copy these lumps to raw files\n\
 -f <rawfile> : copy raw file to lump (guessing lumpname)\n\
 -F <rawfile> : copy raw file to lump (adding to current)\n\
 -n <s> <d>   : copy lump 's' to lump 'd'\n\
\n", 659},
  {"copying *(%s) -> %s(%s)\n", 660},
  {"copying %s -> %s(%s)", 661},
  {"copying *(%s) -> %s(%s)", 662},
  {"copying *(%s) -> %s", 663},
  {"You must select exactly two lines.", 664},
  {"Lines don't cross.", 665},
  {"first vertex is %d, angle %f", 666},
  {"  vertex %d, angle is %f", 667},
  {"connecting %d -> %d", 668},
  {"%d and %d are already connected", 669},
  {"No vertices were connected.", 670},
  {"Some vertices were not connected.", 671},
  {"There must be exactly two lines connected to the selected vertex.", 672},
  {"You must select two one-sided sector boundaries.", 673},
  {"Sector does not seem corridor-like.", 674},
  {"No Create function for this mode yet!", 675},
  {"Flat", 676},
  {"Wall", 677},
  {"Sprite", 678},
  {"Patch", 679},
  {" Texture Browser", 680},
  {"OK!", 681},
  {"Cancel", 682},
  {"Preview", 683},
  {"RotState:", 684},
  {"Rotate", 685},
  {"Advance", 686},
  {"Phase:", 687},
  {"Animate", 688},
  {"Sprite:", 689},
  {"SpriteSize:", 690},
  {"Init", 691},
  {"Detect", 692},
  {"Fight", 693},
  {"Special", 694},
  {"Ouch", 695},
  {"Die", 696},
  {"Explode", 697},
  {"ID:", 698},
  {"\
Usage: %s [OPTION]... [WADFILE]...\n\
Interactively view ProtoThings in X11.\n\
\n", 699},
  {"\
  -w, --load-wad=FILE    load FILE as a WAD.  WADFILE argument does the \
same.\n\
  -s, --no-sound         don't try to play sounds\n\
  -d, --display=DISPLAY  use X display DISPLAY\n\
  -l, --log-to=FILE      save messages to FILE\n\
  -v, --verbose          log to the screen\n\
      --help             display this help and exit\n\
      --version          output version information and exit\n\
\n", 700},
  {"\
If no WADFILE nor --load-wad=FILE arguments are given, XProtoThing\n\
loads `doom2.wad'.\n\
\n", 701},
  {"%s: internal limit on wad files exceeded\n", 702},
  {"no PROTOS lump in wad", 703},
  {"no protos", 704},
  {"Level Saved.", 705},
  {"\
Usage: %s [OPTION]... [WADFILE]...\n\
Interactively edit DUMB levels in X11.\n\
\n", 706},
  {"\
  -w, --load-wad=FILE    load FILE as a WAD.  WADFILE argument does the \
same.\n\
  -m, --map=MAPNAME      start editing map MAPNAME (default E1M1)\n\
  -d, --display=DISPLAY  use X display DISPLAY\n\
  -l, --log-to=FILE      save messages to FILE\n\
  -v, --verbose          log to the screen\n\
      --help             display this help and exit\n\
      --version          output version information and exit\n\
\n", 707},
  {"\
If no WADFILE nor --load-wad=FILE arguments are given, XWad loads\n\
`doom.wad' if the map name begins with `E' and `doom2.wad' otherwise.\n\
\n", 708},
  {"BigMap", 709},
  {"VerMode", 710},
  {"Load:", 711},
  {"LineMode", 712},
  {"Save As:", 713},
  {"SectMode", 714},
  {"Prev", 715},
  {"Next", 716},
  {"ThingMode", 717},
  {"Grid:", 718},
  {"Sprites", 719},
  {"Zoom In", 720},
  {"Zoom Out", 721},
  {"Scale:", 722},
  {"Vertex #", 723},
  {"X-coord", 724},
  {"Y-coord", 725},
  {"Connect", 726},
  {"CCW", 727},
  {"JoinLines", 728},
  {"Sect #", 729},
  {"FloorLvl", 730},
  {"CeilingLvl", 731},
  {"Floor", 732},
  {"Ceiling", 733},
  {"Light", 734},
  {"Type", 735},
  {"Tag", 736},
  {"Stairs", 737},
  {"BigStairs", 738},
  {"Thing #", 739},
  {"Easy", 740},
  {"Delete", 741},
  {"Medium", 742},
  {"Multi", 743},
  {"Hard", 744},
  {"Deaf", 745},
  {"Angle", 746},
  {"Line #", 747},
  {"VerFlip", 748},
  {"SideFlip", 749},
  {"Impassible", 750},
  {"TwoSided", 751},
  {"M-Impass", 752},
  {"UnpUpper", 753},
  {"UnpLower", 754},
  {"Secret", 755},
  {"BlockSnd", 756},
  {"NoMap", 757},
  {"ForceMap", 758},
  {"Poster", 759},
  {"Crossing", 760},
  {"Split", 761},
  {"MkSector", 762},
  {"Corridor", 763},
  {"Side #", 764},
  {"Sector #", 765},
  {"Offset", 766},
  {"Texture", 767},
  {"U-Texture", 768},
  {"L-Texture", 769},
};

int _msg_tbl_length = 769;
